"use client";
import Link from "next/link";
import {onAuthStateChanged,signInAnonymously,type User} from "firebase/auth";
import {useEffect,useState} from "react";
import {auth} from "@/lib/firebase/client";
import {getCustomerOrders,type FoodOrder} from "@/lib/firebase/data";

function label(status:string){return status==="New"?"Request received":status==="Collected"||status==="Delivered"?"Completed":status}
function dateText(value:string){const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString("en-GB",{weekday:"short",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):value}

export default function AccountPage(){
 const[user,setUser]=useState<User|null>(null),[orders,setOrders]=useState<FoodOrder[]>([]),[ready,setReady]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const stop=onAuthStateChanged(auth,next=>{setUser(next);if(next){void getCustomerOrders(next.uid).then(setOrders).catch(()=>setError("Your bookings could not be loaded right now.")).finally(()=>setReady(true))}else setReady(true)});return stop},[]);
 async function startGuest(){setError("");try{const next=(await signInAnonymously(auth)).user;setUser(next);setOrders(await getCustomerOrders(next.uid))}catch{setError("We couldn't start your private booking session. Please try again.")}}
 return <main className="jtsBookingPage"><div className="jtsContainer jtsBookingWrap"><div className="jtsBookingTop"><Link href="/" className="jtsBack">← JTS Styles</Link><Link href="/order" className="jtsGhost">Book appointment</Link></div><section className="jtsBookingIntro"><span className="jtsEyebrow">MY APPOINTMENTS</span><h1>Your bookings.</h1><p>Keep track of appointment requests from this device. You do not need a password to book.</p></section>{!user&&<section className="jtsConfirmation" style={{marginTop:0}}><span className="jtsEyebrow">GUEST ACCESS</span><h2 style={{fontFamily:"Georgia,serif",fontWeight:500}}>Start with your private booking session.</h2><p>Your booking history is tied to a secure guest session on this device. An optional account connection can be added later.</p><button className="jtsButton jtsButtonGold" type="button" onClick={()=>void startGuest()} disabled={!ready}>Open my bookings</button></section>}{user&&<section className="jtsAccountList">{orders.length===0?<div className="jtsConfirmation" style={{marginTop:0}}><span className="jtsEyebrow">NO BOOKINGS YET</span><h2 style={{fontFamily:"Georgia,serif",fontWeight:500}}>Your first look starts here.</h2><p>Choose a service, select a future date and request your appointment.</p><Link href="/order" className="jtsButton jtsButtonGold">Book your first appointment →</Link></div>:orders.map(order=><article key={order.id} className="jtsBookingRow"><div><span className="jtsEyebrow">{label(order.status)}</span><h2>{order.items.map(item=>item.name).join(" · ")}</h2><p>{dateText(order.scheduledFor)}</p><small>Reference #{order.id.slice(0,8).toUpperCase()} · Request status: {order.status}</small></div><Link href={"/orders/"+order.id} className="jtsGhost">View booking</Link></article>)}</section>}{error&&<p className="jtsFormError" role="alert">{error}</p>}<div className="jtsAccountNote"><strong>Remember:</strong> a request is not a confirmed appointment until John confirms the slot and the required deposit is received. For help, call +267 78 053 564.</div></div></main>
}